//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinNET.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoinNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Join.NET に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string button_add {
            get {
                return ResourceManager.GetString("button_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string button_add_connection {
            get {
                return ResourceManager.GetString("button_add_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string button_cancel {
            get {
                return ResourceManager.GetString("button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string button_logout {
            get {
                return ResourceManager.GetString("button_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cmb_lang_en_us {
            get {
                return ResourceManager.GetString("cmb_lang_en_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanease に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cmb_lang_ja_jp {
            get {
                return ResourceManager.GetString("cmb_lang_ja_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_about {
            get {
                return ResourceManager.GetString("label_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto html creation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_auto_html {
            get {
                return ResourceManager.GetString("label_cfg_auto_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_browse {
            get {
                return ResourceManager.GetString("label_cfg_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_enable {
            get {
                return ResourceManager.GetString("label_cfg_enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_ipaddress {
            get {
                return ResourceManager.GetString("label_cfg_ipaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_portnumber {
            get {
                return ResourceManager.GetString("label_cfg_portnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Public Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_public_folder {
            get {
                return ResourceManager.GetString("label_cfg_public_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Internal Web Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_use_web_server {
            get {
                return ResourceManager.GetString("label_cfg_use_web_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transfer any port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_cfg_user_any_port {
            get {
                return ResourceManager.GetString("label_cfg_user_any_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_config {
            get {
                return ResourceManager.GetString("label_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server conection status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_connection_status {
            get {
                return ResourceManager.GetString("label_connection_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Langueage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_language {
            get {
                return ResourceManager.GetString("label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_login {
            get {
                return ResourceManager.GetString("label_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Any protocol tranfer mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_message_mode {
            get {
                return ResourceManager.GetString("label_message_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_password {
            get {
                return ResourceManager.GetString("label_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_signup {
            get {
                return ResourceManager.GetString("label_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_tuunel_port_number {
            get {
                return ResourceManager.GetString("label_tuunel_port_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string label_userid {
            get {
                return ResourceManager.GetString("label_userid", resourceCulture);
            }
        }
    }
}
